# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_read_packedancestrymap <- function(genofile, nsnp, nind, indvec, first, last, transpose = FALSE, verbose = TRUE) {
    .Call(`_smartsnp_cpp_read_packedancestrymap`, genofile, nsnp, nind, indvec, first, last, transpose, verbose)
}

