on:
  push:
    branches:
      - main
      - master

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'  # You can change this if needed

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        run: |
          install.packages("remotes", repos = "https://cloud.r-project.org")
          remotes::install_deps(dependencies = TRUE)
          install.packages("pkgdown", repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      - name: Build and deploy pkgdown site
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
